# Generated by Django 5.1.5 on 2025-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('c_password', models.CharField(max_length=8)),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
