# Generated by Django 5.1.5 on 2025-02-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
    ]
