# Generated by Django 5.1.5 on 2025-02-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='Product',
            new_name='product',
        ),
    ]
