# Generated by Django 5.1.5 on 2025-02-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_color_product_product_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Color_filter',
        ),
        migrations.RenameField(
            model_name='color_filter',
            old_name='product_color',
            new_name='p_color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Color',
            new_name='Color_filter',
        ),
    ]
