# Generated by Django 5.1.5 on 2025-02-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_color_color_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_size', models.CharField(max_length=20)),
            ],
        ),
    ]
