# Generated by Django 5.1.5 on 2025-02-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_size_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Size_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.size_filter'),
        ),
    ]
