# Generated by Django 5.1.5 on 2025-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
