# Generated by Django 5.1.5 on 2025-03-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Total',
        ),
    ]
