# Generated by Django 5.1.5 on 2025-03-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_wishlist_delete_add_to_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
    ]
