# Generated by Django 5.1.5 on 2025-03-27 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_wishlist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='dept_image'),
            preserve_default=False,
        ),
    ]
