# Generated by Django 5.1.5 on 2025-03-30 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_department_dept_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('product_price', models.IntegerField()),
                ('product_detail', models.CharField(max_length=150)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
