# Generated by Django 5.1.5 on 2025-03-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_shop_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='Product Images'),
        ),
        migrations.AlterField(
            model_name='shop_details',
            name='product_detail',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='shop_details',
            name='product_image',
            field=models.ImageField(upload_to='SHOP_DET_IMAGES'),
        ),
    ]
