# Generated by Django 5.1.5 on 2025-04-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop_Details',
        ),
    ]
